[build]
  publish = "public"
  command = "npm install && cd netlify/functions && npm install && cd ../../"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

  [[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
